{
 "title": "CTp6",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CRP1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM CRP1\nORDER BY id"
    }
   ]
  },
  {
   "title": "CRP2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM CRP2\nORDER BY id"
    }
   ]
  },
  {
   "title": "Lada1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM Lada1\nORDER BY id"
    }
   ]
  },
  {
   "title": "Lada2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM Lada2\nORDER BY id"
    }
   ]
  },
  {
   "title": "Lada3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM Lada3\nORDER BY id"
    }
   ]
  },
  {
   "title": "Lada4",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM Lada4\nORDER BY id"
    }
   ]
  },
  {
   "title": "Lada5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM Lada5\nORDER BY id"
    }
   ]
  },
  {
   "title": "Lada6",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM Lada6\nORDER BY id"
    }
   ]
  },
  {
   "title": "Refrigerator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(CAST(CONCAT(date, \" \", time, \":00\") AS datetime)) AS \"time\",\n  temperature\nFROM Refrigerator\nORDER BY id"
    }
   ]
  }
 ]
}